---
title: 'boulders'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(lubridate)
library(ggplot2)
```

```{r}
mydata <- read.csv("HardBoulders2.csv")
mydata$Date <- format(mdy(mydata$Date), "%m/%d/%Y")
head(mydata)
```

```{r}
climbercounts <- table(mydata$Name)
climbercounts <- climbercounts[climbercounts > 12]
ggplot(as.data.frame(climbercounts), aes(x=reorder(Var1, -Freq), y = Freq)) + geom_bar(stat="identity", fill="blue", width=0.5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("Number of Hard Sends by Climber") +
  labs(y="Number", x = "Climber")
ggsave("NumberbyClimber.png", width = 20, height = 20, units = "cm")
```
```{r}
require(dplyr) 
climberFA <- mydata %>% dplyr::filter(FA == "FA")
climberFAcounts <- table(climberFA$Name)
climberFAcounts <- climberFAcounts[climberFAcounts > 7]
ggplot(as.data.frame(climberFAcounts), aes(x=reorder(Var1, -Freq), y = Freq)) + geom_bar(stat="identity", fill="blue", width=0.5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("Number of Hard FA Sends by Climber") +
  labs(y="Number", x = "Climber")
ggsave("NumberFAbyClimber.png", width = 20, height = 20, units = "cm")
```

```{r}
format(as.Date(mydata$Date, format="%m/%d/%Y"),"%Y")
yearcounts <- table(format(as.Date(mydata$Date, format="%m/%d/%Y"),"%Y"))
ggplot(as.data.frame(yearcounts), aes(x=Var1, y = Freq)) + geom_bar(stat="identity", fill="blue", width=0.5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("Hard Boulder Sends by Year") +
  labs(y="Number", x = "Year")
ggsave("Year.png", width = 20, height = 20, units = "cm")
```

```{r}
uniquebygrade <- mydata %>% count(Grade, Name, sort=TRUE) %>% count(Grade, sort=TRUE)
ggplot(uniquebygrade, aes(x=Grade, y = n)) + geom_bar(stat="identity", fill="blue", width=0.3) + 
  ggtitle("Unique Ascentionists by Grade") +
  labs(y="Number", x = "V Grade")
ggsave("Uniquebygrade.png", width = 20, height = 20, units = "cm")
```


```{r}
countrycounts <- table(mydata$Country)
countrycounts <- countrycounts[countrycounts > 12]
ggplot(as.data.frame(countrycounts), aes(x=reorder(Var1, -Freq), y = Freq)) + geom_bar(stat="identity", fill="blue", , width=0.5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("Number of Hard Sends by Country") +
  labs(y="Number", x = "Country")
ggsave("NumberbyCountry.png", width = 20, height = 20, units = "cm")
```

